version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: hyuga_redis
    restart: always
    volumes:
      - "./deploy/redis:/data"

  nginx:
    image: nginx
    container_name: hyuga_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./deploy/nginx:/etc/nginx/conf.d"
      - "./frontend:/var/www"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    command: "/hyuga"
    ports:
      - 127.0.0.1:5000:5000
      - "53:53/udp"
    depends_on:
      - redis
