version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: hyuga_redis
    restart: always
    volumes:
      - "./deploy/redis/data:/data"

  hyuga:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    command: "bash /app/bin/bin.sh"
    ports:
      - 127.0.0.1:5000:5000
      - "53:53/udp"
    volumes:
      - "./:/app"
    depends_on:
      - redis

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - hyuga
    volumes:
      - "./deploy/nginx/conf.d:/etc/nginx/conf.d"
      - "./deploy/nginx/www:/var/www"
